# Default values for simple-flask-app
image: <+artifacts.primary.image>

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001