apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
  namespace: default
  labels:
    app: simple-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
        - name: simple-flask-app
          image: '{{ .Values.image }}'
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5